# -*- coding: utf-8 -*-
"""EntrenarModeloFFT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_usxkXPyEOH1aI-zrmC42poBw0q2_jwV
"""

import os
from google.colab import drive
drive.mount('/content/drive')
os.chdir('/content/drive/My Drive/Colab Notebooks/samples')

import pandas as pd
import numpy as np
import glob
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv1D, MaxPooling1D, Flatten, Dense, Dropout
from tensorflow.keras.regularizers import l2
from tensorflow.keras.callbacks import EarlyStopping
from sklearn.utils.class_weight import compute_class_weight
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from scipy.fftpack import fft
import joblib
from sklearn.metrics import classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns
#librerias para probar distintas formas de balance de datos
from imblearn.combine import SMOTEENN  
from imblearn.combine import SMOTETomek
from imblearn.over_sampling import SMOTE
from imblearn.under_sampling import RandomUnderSampler
from imblearn.under_sampling import NearMiss
from tensorflow.keras.layers import LSTM, Dense, Dropout, Bidirectional
from sklearn.utils import resample

# 1. Configuración
fs = 200  # 200 Hz
window_size = fs * 5  # 5 segundos
stride = fs * 2  # Superposición de 2 segundos

# 2. Funciones de procesamiento de datos
def fft_transform(signal):
    """
    Extrae características usando la transformada de Fourier (FFT).
    Se devuelve la magnitud normalizada de las frecuencias.
    """
    fft_result = np.fft.rfft(signal)
    fft_magnitude = np.abs(fft_result)
    return fft_magnitude[:len(fft_magnitude)//2]

def preprocess_data(df, window_size, stride):
    """
    Preprocesamiento de los datos con desplazamiento de ventanas (stride).
    """
    window_samples = window_size
    stride_samples = stride

    X = []
    y = []

    for i in range(0, len(df) - window_size + 1, stride_samples):
        signal_window = df['signal'][i:i + window_samples]
        bpm_window = df['heart_rate'][i:i + window_samples]
        label = df['seizure'][i + window_samples - 1]

        fft_features = fft_transform(signal_window)

        features = np.concatenate([fft_features, [np.mean(bpm_window)], [np.std(bpm_window)]])
        X.append(features)
        y.append(label)

    return np.array(X), np.array(y)

# 3. Cargar y procesar datos
file_paths = glob.glob('/content/drive/My Drive/Colab Notebooks/samples/*.csv')
X_all, y_all = [], []

for file in file_paths:
    print(f"Procesando {file}...")
    df = pd.read_csv(file)
    df['timestamp'] = df['timestamp'] - df['timestamp'].iloc[0]
    X, y = preprocess_data(df, window_size, stride)
    X_all.append(X)
    y_all.append(y)

X_all = np.vstack(X_all)
y_all = np.concatenate(y_all)

print(f"Tamaño de X_all: {X_all.shape}")
print(f"Tamaño de y_all: {y_all.shape}")

# Normalizar datos
scaler = StandardScaler()
X_all = scaler.fit_transform(X_all)
joblib.dump(scaler, 'scalerFFTFinal.pkl')

# Dividir en entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X_all, y_all, test_size=0.2, random_state=42)

# Pesos de clase
class_weights = compute_class_weight('balanced', classes=np.unique(y_train), y=y_train)
class_weights_dict = dict(enumerate(class_weights))

# Oversampling
X_train_oversampled, y_train_oversampled = resample(
    X_train[y_train == 1], y_train[y_train == 1],
    replace=True,
    n_samples=X_train[y_train == 0].shape[0],
    random_state=42
)

X_train_resampled = np.vstack([X_train[y_train == 0], X_train_oversampled])
y_train_resampled = np.concatenate([y_train[y_train == 0], y_train_oversampled])

print(f"Clase 0 (No ataque) después: {np.sum(y_train_resampled == 0)} | Clase 1 (Ataque) después: {np.sum(y_train_resampled == 1)}")

# Reshape para CNN
X_train_resampled = X_train_resampled.reshape(-1, X_train_resampled.shape[1], 1)

# 5. Crear modelo ANN
model = Sequential([
    Conv1D(64, kernel_size=5, activation='relu', input_shape=(X_all.shape[1], 1), kernel_regularizer=l2(0.01)),
    MaxPooling1D(pool_size=2),
    Conv1D(128, kernel_size=5, activation='relu', kernel_regularizer=l2(0.01)),
    MaxPooling1D(pool_size=2),
    Flatten(),
    Dense(128, activation='relu', kernel_regularizer=l2(0.01)),
    Dropout(0.5),
    Dense(1, activation='sigmoid')
])

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

early_stopping = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)

# 6. Entrenar modelo
history = model.fit(
    X_train_resampled, y_train_resampled,
    epochs=50,
    batch_size=32,
    class_weight=class_weights_dict,
    validation_data=(X_test, y_test),
    callbacks=[early_stopping],
    verbose=1
)

# 7. Guardar modelo
model.save('ModeloFFTFinal.h5')

# 8. Evaluar modelo
y_pred_proba = model.predict(X_test)
threshold = 0.5
y_pred_adjusted = (y_pred_proba > threshold).astype(int)

# 9. Reporte de clasificación
print("Matriz de confusión:")
print(confusion_matrix(y_test, y_pred_adjusted))

print("Reporte de clasificación:")
print(classification_report(y_test, y_pred_adjusted))

# 10. Matriz de confusión normalizada
cm = confusion_matrix(y_test, y_pred_adjusted, normalize='true')
plt.figure(figsize=(6,5))
sns.heatmap(cm, annot=True, fmt='.2f', cmap='Blues',
            xticklabels=['Erasoa ez', 'Erasoa'], yticklabels=['Erasoa ez', 'Erasoa'])
plt.xlabel('Iragarpena')
plt.ylabel('Erreala')
plt.title('nahasketa matrizea (normalizatua)')
plt.show()

# 11. Gráficos de performance
plt.figure(figsize=(12,5))
plt.subplot(1,2,1)
plt.plot(history.history['accuracy'], label='Zehaztasuna')
plt.xlabel('Epokak')
plt.ylabel('Zehaztasuna')
plt.legend()
plt.title('Entrenamenduan zeharreko Zehaztasuna')

plt.subplot(1,2,2)
plt.plot(history.history['loss'], label='Galera')
plt.xlabel('Epokak')
plt.ylabel('Galera')
plt.legend()
plt.title('Entrenamenduan zeharreko galera')

plt.show()
